- defaults:
    link:
      create: true
      relink: true

- create: ['~/.ssh']

- clean: ['~', '~/.config', '~/.ssh']

- link:
    ~/.bashrc_local_after:
    ~/.dotfiles_local: ''
    ~/.gitconfig_local:
    ~/.hammerspoon:
    ~/.name:
    ~/.shell_local_after:
    ~/.shell_local_before:
    ~/.ssh/config: ssh/config
    ~/.ssh/config_local: ssh/config_local

- shell:
  - git submodule sync --recursive
  - git update-submodules # after linking ~/.gitconfig
  - ./macos
