- defaults:
    link:
      create: true
      relink: true


- clean: ['~', '~/.config']

- link:
    ~/.dotfiles_local: ''
    ~/.gitconfig_local:
    ~/.shell_local_after:

- shell:
  - git submodule sync --recursive
  - git update-submodules # after linking ~/.gitconfig
