[env]
TERM = "xterm-256color"

[[colors.indexed_colors]]
color = "#fe8019"
index = 16

[[colors.indexed_colors]]
color = "#d65d0e"
index = 17

[[colors.indexed_colors]]
color = "#3c3836"
index = 18

[[colors.indexed_colors]]
color = "#504945"
index = 19

[[colors.indexed_colors]]
color = "#bdae93"
index = 20

[[colors.indexed_colors]]
color = "#ebdbb2"
index = 21

# moonfly theme for Alacritty
#
# Upstream: github.com/bluz71/vim-moonfly-colors

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#949494"
blue = "#74b2ff"
cyan = "#85dc85"
green = "#36c692"
magenta = "#ae81ff"
red = "#ff5189"
white = "#e4e4e4"
yellow = "#c6c684"

[colors.cursor]
cursor = "#8e8e8e"
text = "#080808"

[colors.normal]
black = "#323437"
blue = "#80a0ff"
cyan = "#79dac8"
green = "#8cc85f"
magenta = "#cf87e8"
red = "#ff5d5d"
white = "#c6c6c6"
yellow = "#e3c78a"

[colors.primary]
background = "#080808"
bright_foreground = "#eeeeee"
foreground = "#bdbdbd"

[colors.selection]
background = "#b2ceee"
text = "#080808"

[font]
size = 15.0

[font.normal]
family = "Noto Sans Mono"

[window]
decorations = "none"

[cursor]
vi_mode_style = "Underline"

[window.dimensions]
columns = 100
lines = 40

[window.padding]
x = 5
y = 5

[selection]
save_to_clipboard = true
semantic_escape_chars = "|:\"' {}()[]<>"

[keyboard]
bindings = [
    { key = "j", mods = "Command", action = "ScrollHalfPageUp"},
    { key = "k", mods = "Command", action = "ScrollHalfPageDown"},
]
