[env]
TERM = "xterm-256color"

[[colors.indexed_colors]]
color = "#fe8019"
index = 16

[[colors.indexed_colors]]
color = "#d65d0e"
index = 17

[[colors.indexed_colors]]
color = "#3c3836"
index = 18

[[colors.indexed_colors]]
color = "#504945"
index = 19

[[colors.indexed_colors]]
color = "#bdae93"
index = 20

[[colors.indexed_colors]]
color = "#ebdbb2"
index = 21

[colors.cursor]
cursor = "0xd5c4a1"
text = "0x1d2021"

# Default colors
[colors.primary]
background = '#181818'
foreground = '#d8d8d8'

# Normal colors
[colors.normal]
black   = '#181818'
red     = '#ab4642'
green   = '#a1b56c'
yellow  = '#f7ca88'
blue    = '#7cafc2'
magenta = '#ba8baf'
cyan    = '#86c1b9'
white   = '#d8d8d8'

# Bright colors
[colors.bright]
black   = '#585858'
red     = '#ab4642'
green   = '#a1b56c'
yellow  = '#f7ca88'
blue    = '#7cafc2'
magenta = '#ba8baf'
cyan    = '#86c1b9'
white   = '#f8f8f8'

[font]
size = 15.0

[font.normal]
family = "Noto Sans Mono"

[window]
decorations = "none"

[cursor]
vi_mode_style = "Underline"

[window.dimensions]
columns = 100
lines = 40

[window.padding]
x = 5
y = 5

[selection]
save_to_clipboard = true
semantic_escape_chars = "|:\"' {}()[]<>"

[keyboard]
bindings = [
    { key = "j", mods = "Command", action = "ScrollHalfPageUp"},
    { key = "k", mods = "Command", action = "ScrollHalfPageDown"},
]
