[env]
term = "xterm-256color"

[[colors.indexed_colors]]
color = "#fe8019"
index = 16

[[colors.indexed_colors]]
color = "#d65d0e"
index = 17

[[colors.indexed_colors]]
color = "#3c3836"
index = 18

[[colors.indexed_colors]]
color = "#504945"
index = 19

[[colors.indexed_colors]]
color = "#bdae93"
index = 20

[[colors.indexed_colors]]
color = "#ebdbb2"
index = 21

[colors.cursor]
cursor = "0xd5c4a1"
text = "0x1d2021"

# Default colors
[colors.primary]
background = "0x1d2021"
foreground = "0xd5c4a1"

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'


[font]
size = 15.0

[font.normal]
family = "Noto Sans Mono"

[window]
decorations = "none"

[cursor]
vi_mode_style = "Underline"

[window.dimensions]
columns = 100
lines = 30

[window.padding]
x = 8
y = 5

[selection]
save_to_clipboard = true
semantic_escape_chars = "|:\"' {}()[]<>"

[keyboard]
bindings = [
    { key = "j", mods = "Command", action = "ScrollHalfPageUp"},
    { key = "k", mods = "Command", action = "ScrollHalfPageDown"},
]
